apiVersion: v1
kind: Service
metadata:
  name: {{ include "greetings-api.fullname" . }}
  labels:
    {{- include "greetings-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "greetings-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
