apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-collector-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: stg
          - env: prod
  template:
    metadata:
      name: 'otel-collector-{{env}}'
      labels:
        app: otel-collector
        env: '{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/glexposito/k8s-playground.git
        targetRevision: HEAD
        path: charts/otel-collector
        helm:
          valueFiles:
            - values.yaml
            - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'otel-collector-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
