apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pulse-api-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: stg
          - env: prod
  template:
    metadata:
      name: 'pulse-api-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/glexposito/k8s-playground.git
        targetRevision: HEAD
        path: charts/pulse-api
        helm:
          valueFiles:
            - values.yaml
            - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pulse-api-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
