nameOverride: ""
fullnameOverride: ""

replicaCount: 3

image:
  repository: ghcr.io/glexposito/pulse-api
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5
  liveness:
    path: /live
    initialDelaySeconds: 15
    periodSeconds: 10

rollingUpdate:
  maxUnavailable: 0
  maxSurge: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
